name = "test"
main = "index.js"
compatibility_date = "2025-09-09"
# compatibility_flags = []
# node_compat = true
# keep_vars = true

# [triggers]
# crons = ["*/5 * * * *"]

# [vars]

# [assets]
# directory = "./public"
# binding = "ASSETS"

# [wasm_modules]
# WASM_PARSER = "./wasm/parser.wasm"

# [text_blobs]
# EMAIL_TEMPLATE = "./templates/welcome.txt"

# [data_blobs]
# BINARY_CHUNK = "./assets/blob.bin"

# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-db"
# database_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [durable_objects]
# bindings = [{ name = "MY_DO", class_name = "MyDurableObject" }]

# [[migrations]]
# tag = "v1"
# new_classes = ["MyDurableObject"]

[[d1_databases]]
binding = "SUNE_PLATFORM_USERS"
database_name = "sune_platform_users"
database_id = "464b291c-90a5-4947-b96b-b1b5aeca1db3"

[[d1_databases]]
binding = "HI"
database_name = "hi"
database_id = "45ee691d-3d0c-42f2-8e3a-35a369444a03"

[[d1_databases]]
binding = "SUNE"
database_name = "sune"
database_id = "140c5f3d-c4d4-4cdf-b520-a23366172971"
